repos:
-   repo: https://github.com/ambv/black
    rev: 22.6.0
    hooks:
    - id: black

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
      args: ['--config=setup.cfg']

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971
    hooks:
    -   id: mypy
    