xversion: '3.5'
services:
  database:
    container_name: ishango_postgres
    image: postgres:latest
    environment:
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASS}"
      - "POSTGRES_DB=${POSTGRES_DB}"
    ports:
      - 5432:5432
    volumes:
      - db_volume:/var/lib/postgresql

volumes:
  db_volume:
