name: Black Formatter

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  black-formatter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
        with:
          options: "--line-length 127"
          src: "./src"
